mode: "dev"
port: 8989

log:
  # 日志级别
  level: "debug"
  # 日志分割配置
  filename: "D:/log/bluebell.log"
  max_size: 1000
  max_age: 3000
  max_backups: 5

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123123
  db: go
  max_open_conns: 100
  max_idle_conns: 20

redis:
  # 使用虚拟机Docker容器中的redis
  host: 192.168.18.133
  port: 6379
  # 不使用redis集群
  db: 0
